### ISSUE TITLE
Provide description and documentation

### ISSUE THREAD

**Issue by hatalmasalma** [eldertek/duplicatefinder#109]
The Github repo is not listed properly in the Nextcloud store, only accessible through the buttons.
Not only that, basically there is no description in the Nextcloud store.

Even after finding this repo, there barely any documentation on what does this addon exactly do.

What does backgroundjob_interval_cleanup mean?
Will it delete files from my servers?
Will I have to confirm them?
How can I whitelist things?
Can I make sure this addon doesn't delete referenced files?

So many basic information is missing.

If this is WIP, please provide this information in the store description.

**Comment by eldertek** [comment]
On the Appstore, currently, the repository is mentioned in the "Report problem" and "Request feature" sections ([GitHub Repo](https://apps.nextcloud.com/apps/duplicatefinder)). What did you suggest in plus ?

Documentation on key settings and configurations has been added in v1.1.1.

The cleanup job only affects database records and does not delete any actual files from storage.
It is a safe maintenance operation intended to improve database performance by removing outdated entries.
Users do not need to confirm these operations, as they are safe and non-intrusive.

**Comment by hatalmasalma** [comment]
Thank you for your explanation.

Regarding the Appstore links:
Most addons have some of these links beside the buttons:
![Screenshot 2024-12-26 at 19-28-24 Contacts - Apps - App Store - Nextcloud](https://github.com/user-attachments/assets/323e3117-4e2f-4378-bf89-184e1639419d)

Maybe it's just my personal quirk, but I barely looked at those buttons before, always expected a link with the proper description.
It's up to you to add a link as homepage.

However, some more elaborate description and admin documentation would really be helpful.

**Comment by eldertek** [comment]
I've added links in the Nextcloud App Store similar to the ones shown in the screenshot you provided. These should make it easier to access relevant resources directly from the app store page.

Regarding the documentation: I currently do not plan to create dedicated user or admin documentation. The app's functionality is designed to be minimal and straightforward, so I believe it doesn't require extensive external documentation. However, if you have specific questions or need clarification about certain features or sections, feel free to reach out. I'll be happy to add small explanatory "mini-docs" directly within the app where needed, rather than maintaining a separate, full-fledged documentation.

**Comment by hatalmasalma** [comment]
Thank you very much for implementing my suggestions.
Now everything is nice and tidy 👍
The rest is indeed straightforward.

Keep up the good work ❤

**Comment by eldertek** [comment]
@hatalmasalma  I recommend installing v1.4.1, which includes a new help bullet that might interest you.
If you haven’t already, feel free to star the project ⭐ to support us.

Cheers! 🎉
