### ISSUE TITLE
Memory exhausted error on upgrade to 1.1.4

### ISSUE THREAD

**Issue by robertoschwald** [eldertek/duplicatefinder#35]
On update to the latest version 1.1.4, NC failed and entered maintenance mode. 

Log:
Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) at /var/www/html/lib/public/AppFramework/Db/Entity.php#208

I needed to disable the duplicate finder app using occ to get the system working again.

NC Version: 27.1.3.2
PHP: 8.1.25

**Comment by eldertek** [comment]
It seems like the issue is related to memory exhaustion. To address this, you can try increasing the PHP memory limit. Locate your PHP configuration file (often php.ini) and update the memory_limit directive to a higher value.

On 23 November 2023 19:20:06 CET, Robert Oschwald ***@***.***> wrote:
>On update to the latest version 1.1.4, NC failed and entered maintenance mode. 
>
>Log:
>Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) at /var/www/html/lib/public/AppFramework/Db/Entity.php#208
>
>I needed to disable the duplicate finder app using occ to get the system working again.
>
>NC Version: 27.1.3.2
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/eldertek/duplicatefinder/issues/35
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
En vous remerciant,
Cordialement.

---
André Théo LAURET 
Étudiant en Classe Préparatoire Technologie et Sciences Industrielles | Lycée Polyvalent de Cachan
☎ 07.65.15.58.39 | ✉ ***@***.***
