### ISSUE TITLE
Multiselect or some sort of marked for autodeletion possible?

### ISSUE THREAD

**Issue by Moep90** [eldertek/duplicatefinder#39]
Hey there,

I often import many documents at once and I now for example have 10000+ Documents marked as duplicates (which seams to be correct).

Now I can't really delete them manually and therefore I'd like to have some sort of automatically deletion (after adding respective files to the list) or simply get a multi select with marking file A and press shift and click on file Z.

Cheers and best regards!

**Comment by Dungeonminez** [comment]
Same situation for me. I have thousands of family photos imported from Google Photos with countless duplicates. A multi-select or auto-delete would be worth gold! Thanks for looking into it :)

**Comment by eldertek** [comment]
Hello, I would be highly motivated to develop the feature swiftly with your support.

https://patreon.com/eldertek

**Comment by eldertek** [comment]
I added some new functionalities related to the issue. Can you guys give me your feedback? v1.1.11

**Comment by eldertek** [comment]
Up ?

**Comment by steadfasterX** [comment]
> I added some new functionalities related to the issue. Can you guys give me your feedback? v1.1.11

many thanks for the new changes!

one can multi-select now (hold and scroll down) but unfortunately this is useful for a few pics only.. if you have multiple thousands it will take ages to scroll up to the bottom.. 

it would be great having that requested "select all" button (near the top e.g.)

**Comment by eldertek** [comment]
I have just added the "Select All" button at the top of the list. Now you can quickly select all files + right now files are deleted in parallels to avoid long processing.

Version 1.2.3

**Comment by eldertek** [comment]
Closing as completed

**Comment by aaron01-dev** [comment]
Would love a feature to bulk delete oldest or latest duplicate groups

say:

Group A
File - 1 date: 1/1/24
File - 2 date: 1/2/24
File - 3 date: 1/3/24

Group B
File 1 date: 4/1/24
File 2 date: 6/1/24
File 3 date: 10/1/24

Not necesarily stating Group A B C since it's pretty self explanatory based on preview or simply add an alternating no border + bordered for each group.

Or in the meantime at least **show the date modified** of each file and have a **sort by date** for each duplicate group.
