### ISSUE TITLE
Performance issue (RAM usage) making the tab crash

### ISSUE THREAD

**Issue by remz1337** [eldertek/duplicatefinder#45]
I'm guessing my setup is an extreme case (although I only have 2 users) but I have a LOT of duplicates  (probably a few thousands, a mix of pictures and documents) but now that I've resolved the initial scan (issue https://github.com/eldertek/duplicatefinder/issues/43) and I'm able to see my duplicates in the web page, I'm running into performance issue.

Watching the browser network logs, I see it takes about 200ms to retrieve 1 duplicate. At about 500 duplicates, the tab used 250MB of RAM. At 1000 duplicates the tab used about 1.5Gb... The tab becomes slowly inaccessible.

- quick solution: Limit the number of duplicates loaded to 100. Once those are cleaned, I can reload the page to see the next 100.
- good solution: implement pagination
- best? solution: optimize ram usage (not sure what can be done...)

**Comment by eldertek** [comment]
I'm not sure ram usage can be reduced.
I think the best and quick solution is limit number of duplicates.

There is already a pagination, but (it is tricky to explain)

In DB, it exists
Duplicate 1, id = 0
Duplicate 2, id = 1
Duplicate n, id = n-1
Duplicate n + 1, id = n

The problem the user don't have access to all files associated to duplicates from 1 to n+1 (in general)

So when the user asks for theirs duplicated files.
The program returns only duplicates which have files the user can access.

For doing this, it checks the duplicates with id < 50, it is page 1. For page 2 it checks the duplicates with 50 <  id < 100. Etc etc.

So if you have very lot of duplicates, and you don't have access to page 1 and 2, the program will continue to find the page you have duplicates in. Resulting in a lot of pages. 

So that's the reason the web page async load your duplicates, it is the time for it to find all your duplicates

**Comment by remz1337** [comment]
Ok I see, then is it possible to make it stop after a certain amount of duplicates is returned?

**Comment by eldertek** [comment]
I will integrate this when having time ;) browser side

**Comment by eldertek** [comment]
Fixed by v1.1.5, only available on Nextcloud 28. (the page stop fetching data from server after 40 duplicates has been delivered)
