### ISSUE TITLE
Issue while running duplicate finder from CLI

### ISSUE THREAD

**Issue by argoyal** [eldertek/duplicatefinder#47]
I am trying to a run duplicate finder on a very large Nextcloud directory almost 400 GB. I run the command

`sudo -u www-data php occ duplicate:find-all -u admin`

and receive the following error

```
In Cache.php line 354:

  File entry could not be inserted but could also not be selected with getId() in order to perform an update. P
  lease try again.

```

Can someone help what might be the issue and how to fix this?

Full trace

```
Exception trace:
  at /var/www/html/lib/private/Files/Cache/Cache.php:354
 OC\Files\Cache\Cache->insert() at /var/www/html/lib/private/Files/Cache/Scanner.php:300
 OC\Files\Cache\Scanner->addToCache() at /var/www/html/lib/private/Files/Cache/Scanner.php:233
 OC\Files\Cache\Scanner->scanFile() at /var/www/html/lib/private/Files/Cache/Scanner.php:460
 OC\Files\Cache\Scanner->handleChildren() at /var/www/html/lib/private/Files/Cache/Scanner.php:397
 OC\Files\Cache\Scanner->scanChildren() at /var/www/html/lib/private/Files/Cache/Scanner.php:400
 OC\Files\Cache\Scanner->scanChildren() at /var/www/html/lib/private/Files/Cache/Scanner.php:400
 OC\Files\Cache\Scanner->scanChildren() at /var/www/html/lib/private/Files/Cache/Scanner.php:347
 OC\Files\Cache\Scanner->scan() at /var/www/html/lib/private/Files/Utils/Scanner.php:273
 OC\Files\Utils\Scanner->scan() at /var/www/html/custom_apps/duplicatefinder/lib/Utils/ScannerUtil.php:64
 OCA\DuplicateFinder\Utils\ScannerUtil->scan() at /var/www/html/custom_apps/duplicatefinder/lib/Service/FileInfoService.php:262
 OCA\DuplicateFinder\Service\FileInfoService->scanFiles() at /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php:171
 OCA\DuplicateFinder\Command\FindDuplicates->findDuplicates() at /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php:152
 OCA\DuplicateFinder\Command\FindDuplicates->OCA\DuplicateFinder\Command\{closure}() at /var/www/html/lib/private/User/Manager.php:551
 OC\User\Manager->callForAllUsers() at /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php:153
 OCA\DuplicateFinder\Command\FindDuplicates->findAllDuplicates() at /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php:114
 OCA\DuplicateFinder\Command\FindDuplicates->execute() at /var/www/html/3rdparty/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:206
 OC\Console\Application->run() at /var/www/html/console.php:100
 require_once() at /var/www/html/occ:11
```

Versions of the software

Nextcloud Hub 7 - (28.0.2)
Using AIO latest image to run all the containers

Duplicate Finder - 1.1.4

**Comment by eldertek** [comment]
**I'll provide a comprehensive response to the error you're encountering in Nextcloud Duplicate Finder, incorporating insights from expert feedback and best practices:**

**Understanding the Error:**

- **File Cache Issue:** The error "File entry could not be inserted but could also not be selected with getId()..." indicates a problem with Nextcloud's file cache, likely due to the large directory size or potential database inconsistencies.

**Troubleshooting Steps:**

1. **Check and Repair File Cache:**
   - Run `sudo -u www-data php occ files:scan --all` to scan and repair the file cache.
   - If issues persist, clear the cache manually: `sudo -u www-data php occ files:cleanup`

2. **Optimize Database:**
   - Optimize your database tables (e.g., in MySQL: `OPTIMIZE TABLE oc_filecache, oc_filecache_extended`).

3. **Increase Memory Allocation:**
   - Temporarily increase PHP's memory limit for the Duplicate Finder command: `php -d memory_limit=512M occ duplicate:find-all -u admin`
   - Adjust the value (512M in this example) based on your server resources.

4. **Address Database Issues:**
   - If the above steps don't resolve the issue, consider:
     - Repairing or optimizing database tables using appropriate tools for your database system.
     - Reviewing recent database changes for potential conflicts.

5. **Update Nextcloud and Duplicate Finder:**
   - Ensure you're using the latest versions of Nextcloud and the Duplicate Finder app for compatibility and bug fixes.

**Additional Recommendations:**

- **Break Down Scans:** For large directories, consider scanning in smaller segments to reduce memory usage.
- **Monitor Resources:** Keep an eye on server resources (memory, CPU) during the scan process.
- **Seek Community Help:** If the issue persists, consult the Nextcloud community forums or seek assistance from a qualified Nextcloud administrator.

**Remember:**

- Back up your Nextcloud instance before making significant changes.
- Proceed with caution when modifying database tables or configuration files.

**By following these steps systematically and considering the expert insights, you should be able to effectively address the error and successfully run the Duplicate Finder on your large Nextcloud directory.**
