### ISSUE TITLE
Suggestion: Also detect if two images look similar

### ISSUE THREAD

**Issue by Ellpeck** [eldertek/duplicatefinder#63]
First up, I love this plugin a lot and it's been incredibly useful for cleaning out my media uploads from my phone, especially.

It looks like, currently, the only way that this plugin finds duplicates is through calculating files' hashes (and potentially comparing their sizes, it looks like?). However, for image files, it would be awesome if this plugin also considered their similarity in terms of visuals, Potentially, an algorithm out of the ones [described here](https://stackoverflow.com/a/844113) could be used.

I realize this would be a big undertaking and, of course, I understand if a feature like that is out of the scope of this plugin.

**Comment by Routhinator** [comment]
This app currently uses a basic hashing algorithm which keeps the resource requirements light and the implementation simple. What you are asking for would require some form of ML, and greatly balloon the reqs. 

Not saying it's impossible, but since this app is aimed at staying fairly lightweight and detecting duplicate files of any type - detecting similar images should likely be a wholly separate app.

**Comment by Routhinator** [comment]
Thinking on this more, this is likely a reasonable additional feature for Recgonize as it will fit into that app as a basic feature add on, whereas adding such a thing to this would balloon the code for a feature that's super specific to one type of file and outside the aim of this app.

**Comment by eldertek** [comment]
Hello, thanks for the suggestion but as @Routhinator said, the feature is out of range of DupFinder, so I will not consider adding a feature like this.

You can actually find some existing app for this feature.
