### ISSUE TITLE
[Bug] - since Version 1.2.6, SQLSTATE error

### ISSUE THREAD

**Issue by alexsorel** [eldertek/duplicatefinder#99]
**Describe the bug**
Since upgrade to 1.2.6, Duplicate Finder does not find any duplicate. Logs shows "DbalException
An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "pg_column_size(d" LINE 1: ..."id", "d"."type", "d"."hash", "d"."acknowledged", "pg_column... ^
A unknown exception occurred"

**To Reproduce**
Upgrade to 1.2.6

**Expected behavior**
Expect to revert to previous version status

**Screenshots**
![image](https://github.com/user-attachments/assets/07069a3d-123e-4c1f-b645-973de24d8ad7)
![image](https://github.com/user-attachments/assets/897bc8eb-714e-4bf2-9c69-497cc4dd5566)

**Versions**
- Nextcloud Hub 8 (29.0.7) AIO
- Duplicate Finder 1.2.6

**Comment by Toastyyy3** [comment]
Having the same issue, app is currently unusable with postgres. I believe its due to the following line:
https://github.com/eldertek/duplicatefinder/blob/f806e8ad65ae090b2473bbe05c1883d705d291f7/lib/Db/FileDuplicateMapper.php#L71

Seems to me like a low hanging fruit, unfortunately I've never worked with php so I'm not really aware of the gists of it.

More detailed logs:
<details>
<summary>Logs
</summary>

ERROR:  missing FROM-clause entry for table \"pg_column_size(d\"\nLINE 1: ...\"id\", \"d\".\"type\", \"d\".\"hash\", \"d\".\"acknowledged\", \"pg_column...\n                                                             ^","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1939,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1881,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1106,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":415,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":289,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":313,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Db/FileDuplicateMapper.php","line":74,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Service/FileDuplicateService.php","line":82,"function":"findAll","class":"OCA\\DuplicateFinder\\Db\\FileDuplicateMapper","type":"->"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Utils/CMDUtils.php","line":24,"function":"findAll","class":"OCA\\DuplicateFinder\\Service\\FileDuplicateService","type":"->"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php","line":189,"function":"showDuplicates","class":"OCA\\DuplicateFinder\\Utils\\CMDUtils","type":"::"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php","line":142,"function":"findDuplicates","class":"OCA\\DuplicateFinder\\Command\\FindDuplicates","type":"->"},{"file":"/var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php","line":123,"function":"findDuplicatesForUsers","class":"OCA\\DuplicateFinder\\Command\\FindDuplicates","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":298,"function":"execute","class":"OCA\\DuplicateFinder\\Command\\FindDuplicates","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1040,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":183,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/console.php","line":87,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":71,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42P01]: Undefined table: 7 
</details>

**Comment by alfmillan** [comment]
Hi,

I have the same issue, versions tested implemented with nextcloud aio and with docker in truenas...

https://github.com/nextcloud/all-in-one#can-i-run-aio-on-truenas-scale

Versión
[Nextcloud Hub 9] (https://nextcloud.com/) (30.0.2)
Duplicate Finder 1.2.6
PostgreSQL 16.4

Logs:
DbalException
An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "pg_column_size(d" LINE 1: ..."id", "d"."type", "d"."hash", "d"."acknowledged", "pg_column... ^
A unknown exception occurred

**Comment by petrcech** [comment]
Hi,
the statement `'pg_column_size(d.hash) as hash_size'` gets wrongly escaped on the dot with the `addSelect` function as

`SELECT "d"."id" as "id", "d"."type", "d"."hash", "d"."acknowledged", "pg_column_size(d"."hash)" as "hash_size" FROM "oc_duplicatefinder_dups" "d" ORDER BY "hash" ASC, "ty
pe" ASC LIMIT 20`

I'm not sure, how to stop it from doing that.

**Comment by bocklucas** [comment]
I'm experiencing this as well, is there any idea when a fix will be added and a new release made?

**Comment by bocklucas** [comment]
ChatGPT alledges you can correct the bad escaping with the following,

`duplicatefinder/lib/Db/FileDuplicateMapper.php:69`
```
if ($this->db->getDatabasePlatform() instanceof PostgreSQL94Platform ||
    $this->db->getDatabasePlatform() instanceof PostgreSQL100Platform) {
    $qb->addSelect('pg_column_size("d"."hash") as hash_size');
}
```

However I haven't tried this nor am I a PHP expert (only touched it a handful of times in my life)

@eldertek are you able to follow up on this?

**Comment by bocklucas** [comment]
Tried the change out, no dice, looking at other options

**Comment by bocklucas** [comment]
Can someone correct me, but as far as I can tell it looks like that value `hash_size` isn't even being used anywhere. I commented the if statement out in my nextcloud instance and there appears to be progress now, however I can't tell on account of it taking super long.

**Comment by bocklucas** [comment]
@eldertek pulled the new version down and now experiencing this issue,

```
An exception occurred while executing a query: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "[my_username]" CONTEXT: unnamed portal parameter $1 = '...'
```

Seeing this in the output,

```
OC\DB\ConnectionAdapter->executeQuery(
  "SELECT `d`.`id` as `id`, `d`.`type`, `d`.`hash`, `d`.`acknowledged` FROM `*PREFIX*duplicatefinder_dups` `d` WHERE `user_id` = :dcValue1 ORDER BY `hash` ASC, `type` ASC LIMIT 50",
  {
    "dcValue1": "[my_username]"
  },
  {
    "dcValue1": 2
  }
)
```

**Comment by bocklucas** [comment]
> @eldertek pulled the new version down and now experiencing this issue,
> 
> ```
> An exception occurred while executing a query: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "[my_username]" CONTEXT: unnamed portal parameter $1 = '...'
> ```
> 
> Seeing this in the output,
> 
> ```
> OC\DB\ConnectionAdapter->executeQuery(
>   "SELECT `d`.`id` as `id`, `d`.`type`, `d`.`hash`, `d`.`acknowledged` FROM `*PREFIX*duplicatefinder_dups` `d` WHERE `user_id` = :dcValue1 ORDER BY `hash` ASC, `type` ASC LIMIT 50",
>   {
>     "dcValue1": "[my_username]"
>   },
>   {
>     "dcValue1": 2
>   }
> )
> ```

Hoping I didn't screw something up in the copy stage, how I got to this was I downloaded version v1.2.7 to my nextcloud volume, removed the contents of the duplicatefinder folder and then pasted the version v1.2.7 contents into it, matching the files from v1.2.6 and setting the same permissions and ownership

**Comment by eldertek** [comment]
v1.2.7 is not intended to fix the issue; please test v1.2.8 instead.

**Comment by bocklucas** [comment]
Ahh gotcha! I'll give that a go now :grin:

**Comment by bocklucas** [comment]
I don't seem to be getting any errors, the endpoint is timing out for me now though but I think its unrelated to this

**Comment by eldertek** [comment]
Perfect, is the cli giving you the duplicates (find-all) ?

**Comment by bocklucas** [comment]
> Perfect, is the cli giving you the duplicates (find-all) ?

I'll give that a try today but it appears the cron is working, I'm getting duplicates back in the web interface 🎉🎊

**Comment by eldertek** [comment]
Ok closing as completed !
